services:
  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis1234
    command: ["redis-server", "--requirepass", "redis1234", "--databases", "16"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
